Use setup-lando and run-leia-action (#50)
* Update tests to use setup-lando and run-leia-action GitHub actions.

* Correct path to the leia tests.

* Update leia.

* Use .lando.local.yml to set Lagoon plugin dogfooding.

diff --git a/.github/workflows/pr-proxy-tests.yml b/.github/workflows/pr-proxy-tests.yml
--- a/.github/workflows/pr-proxy-tests.yml
+++ b/.github/workflows/pr-proxy-tests.yml
@@ -11,9 +11,9 @@ jobs:
     strategy:
       matrix:
         leia-tests:
-          - examples/proxy-tests
-        lando-versions:
-          - edge
+          - proxy-tests
+        lando-version:
+          - 3-dev
         os:
           - ubuntu-22.04
         node-version:
@@ -30,16 +30,13 @@ jobs:
           cache: yarn
       - name: Install Yarn dependencies
         run: yarn install --prefer-offline --frozen-lockfile
-
-      # This block should eventually become use lando/actions-hyperdrive@v2
-      - name: Verify Docker dependencies
-        run: |
-          docker --version | grep "24.0."
-          docker-compose --version | grep "1.29."
-      - name: Grab latest edge Lando CLI
-        run: |
-          sudo curl -fsSL -o /usr/local/bin/lando "https://files.lando.dev/cli/lando-linux-x64-${{ matrix.lando-versions }}"
-          sudo chmod +x /usr/local/bin/lando
+      - name: Setup lando ${{ matrix.lando-version }}
+        uses: lando/setup-lando@v2
+        with:
+          lando-version: ${{ matrix.lando-version }}
+          config: |
+            plugins.@lando/lagoon=/home/runner/work/lagoon/lagoon
+          telemetry: false
       - name: Find and Replace
         uses: jacobtomlinson/gha-find-replace@v3
         with:
@@ -57,17 +54,15 @@ jobs:
         run: |
           lando version
           lando config --path plugins | grep lagoon | grep /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }} || (echo "::error:: Not dogfooding this plugin correctly! " && exit 1)
-
-      # This block should eventually become use lando/actions-leia@v2
-      # @NOTE? Do we want a way for our leia-action to configure apparmor since
-      # this might break a whole bunch of tests? or is this literally just a thing
-      # for the Lagoon mysql/mariadb container?
-      - name: Configure apparmor
+      - name: Verify Lando works and we are dogfooding this plugin for tests
         run: |
-          set -x
-          sudo apt-get remove mysql-server --purge
-          sudo apt-get install apparmor-profiles
-          sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
-      - name: Run leia tests
-        shell: bash
-        run: yarn leia "./${{ matrix.leia-tests }}/README.md" -c 'Destroy tests' --stdin --shell bash
+          lando version
+          lando config --path plugins | grep lagoon | grep /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }} || (echo "::error:: Not dogfooding this plugin correctly! " && exit 1)
+      - name: Run Leia Tests
+        uses: lando/run-leia-action@v2
+        with:
+          leia-test: "./examples/${{ matrix.leia-tests }}/README.md"
+          cleanup-header: "Destroy tests"
+          shell: bash
+          stdin: true
+          lagoon-mode: true
